### ISSUE TITLE
Drop useless POD

### ISSUE THREAD

**Issue by guimard** [LemonLDAPNG/Authen-WebAuthn#1]
Hi,

you provided WebAuthn.pm with useless POD and WebAuthn.pod. Then built package uses WebAuthn.pm to build manpage. Please drop POD from WebAuthn.pm and WebAuthn/Test.pm

**Comment by maxbes** [comment]
Notifications weren't enabled, sorry for the delay. I fixed this in a8ca6e0. 
Do I need to make a new CPAN release? With a different version (0.002?)

**Comment by guimard** [comment]
Thanks @maxbes, not for me _(I patched Debian package)_, but it is a good thing for other CPAN users.

**Comment by guimard** [comment]
With a different version of course, else package will be rejected

**Comment by maxbes** [comment]
Fixed by a8ca6e0251e3e925541c1bcefec4606906c0cbdc
